# Generated by Django 3.1.7 on 2021-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255, verbose_name='Функция')),
                ('step', models.SmallIntegerField(verbose_name='Шаг')),
                ('bot_interval', models.FloatField(verbose_name='Нижний интервал')),
                ('top_interval', models.FloatField(verbose_name='Верхний интервал')),
                ('data', models.DateField(auto_now=True, verbose_name='дата сохранения')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
                'ordering': ['data'],
            },
        ),
    ]
