# Generated by Django 3.1.6 on 2021-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='figures/'),
        ),
    ]
